fix compilation on mac os
Compiling on mac os fails with the following error:
```
$ make
mkdir -p build
c++ -O2 -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -DPROFILER_VERSION=\"1.7\" -I/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home/include/darwin -fPIC -shared -o build/libasyncProfiler.so src/allocTracer.cpp src/arguments.cpp src/codeCache.cpp src/engine.cpp src/flameGraph.cpp src/flightRecorder.cpp src/frameName.cpp src/instrument.cpp src/itimer.cpp src/javaApi.cpp src/lockTracer.cpp src/mutex.cpp src/os_linux.cpp src/os_macos.cpp src/perfEvents_linux.cpp src/perfEvents_macos.cpp src/profiler.cpp src/stackFrame_aarch64.cpp src/stackFrame_arm.cpp src/stackFrame_i386.cpp src/stackFrame_x64.cpp src/symbols_linux.cpp src/symbols_macos.cpp src/threadFilter.cpp src/vmEntry.cpp src/vmStructs.cpp src/wallClock.cpp -ldl -lpthread
src/symbols_macos.cpp:153:9: error: use of undeclared identifier 'atomicInc'
        atomicInc(count);
        ^
1 error generated.
make: *** [build/libasyncProfiler.so] Error 1
```

It seems to be missing an include (`arch.h`).